### GPT and LLM Model

###  Step 1. Dataset Prepration

In [ ]:
# We always srart with a dataset to train on. Let's download the tiny shakespeare dataset
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-03-20 09:19:43--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  --.-KB/s    in 0.05s   

2024-03-20 09:19:44 (20.1 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [ ]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f: # input.txt file has been opened in read mode in UTF-8 encoding, where as f assigns the file object to variable f.
  text=f.read() # reads the contents of the file object 'f' and returns it as a string 'text'.

In [ ]:
# Finding the Length of the given string 'text'
print("length of dataset in characters:", len(text))

length of dataset in characters: 1115394


In [ ]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [ ]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text))) # set(text) creates a set containing all the unique characters present in the string 'text'
                                # list(set(text)) converts this set back into a list, removing any duplicate characters.
                                # sorted(list(set(text))) sorts the characters in alphabetical orders
                                # Finally, 'chars' is assigned the sorted list of unique characters.

vocab_size = len(chars) # Calculates the length of the list `chars` and value is then assigned to the variable `vocab_size`
print(''.join(chars)) # joins all the characters in this list `chars` into a single string, with no separator between them.
print(vocab_size) # Prints out the number of unique characters


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


### Step 2. Tokenization

In [ ]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) } # This line creates a dictionary `stoi` where the keys are characters from the `chars` list and the values are the corresponding indices of those characters in the `chars` list.
                                             # enumerate(chars) returns an iterator of pairs (index, character) for each character in the chars list.
                                             # { ch:i for i,ch in enumerate(chars) } is a dictionary comprehension that creates the dictionary stoi by iterating over the pairs and setting the character ch as the key and its index i as the value.

itos = { i:ch for i,ch in enumerate(chars) } # It creates a dictionary `itos` where the keys are indices from the `chars` list and the values are the corresponding characters.
                                             # { i:ch for i,ch in enumerate(chars) } is another dictionary comprehension that creates the dictionary itos by iterating over the pairs and setting the index i as the key and its corresponding character ch as the value.

encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [ ]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we us Pytorch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT looks like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

### Step 3. Spliting the dataset in training and validation sets

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n] # Training set
val_data = data[n:] # Validation set

### Step 4. Data loader: batches of chunks of data

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [ ]:
x = train_data[:block_size] # inputs to the transformer
y = train_data[1:block_size+1] # taret for each position in text
for t in range(block_size): # Inside the loop, this line creates a context which is subsequence of the input `x`
    context = x[:t+1] # It slices `x` up to position `t + 1`, inclusively. This context grows with each iteration of the loop.
    target = y[t] # This line selects the target character or token at position `t` from the `y` sequence.
    print(f"when input is {context} the target: {target}") # Pritns output string dynamically with current context and target using f-string.

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [ ]:
torch.manual_seed(1337) # To sets the random seed for Pytorch to ensure reproducibility
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split): # generates a small batch of data for either training or validation based on the value of the `split` parameter
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data # Selects the appropriate dataset based on the value of the `split` parameter.
    # Generates a tensor of random indices (`ix`) within the range of data length minus `block_size`. It is used to select starting positions for each sequence in the batch.
    ix = torch.randint(len(data) - block_size, (batch_size,))
    # Creates a tensor `x` containing the inputs for the batch. It selects sequences of length `block_size` starting from the randomly generated indices.
    x = torch.stack([data[i:i+block_size] for i in ix])
    # Creates a tensor `y` containing the targets for the batch. It selects sequences of length `block_size` starting from the indices shifted by one position to the right.
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train') # Call function to generate a batch of training data.
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1] # Selects the context for the current time step (t) for the sequence (b) in the batch.
        target = yb[b,t] #Selects the target for the current time step (t) for the sequence (b) in the batch.
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

### Step 5. Building Bigram Model, loss, generation

In [ ]:
# Inporting the necessary modules from PyTorch
import torch
import torch.nn as nn
from torch.nn import functional as F

# This sets the random seed for PyTorch to ensure reproducibility
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module): # defines a class named `BigramLanguageModel`; which is a subclass of `nn.Module`
    # Constructor method of the `BigramLanguageModel` class.
    def __init__(self, vocab_size): # Initializes the model and defines its architecture. `vocab_size` is the size of vocabulary.
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    # `forward()` method defines the forward pass of the model.
    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        # It claculates the logits using the embedding table and computes the loss if `targets` are provided
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    #
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size) # Creates an instance of the `BigramLanguageModel`
logits, loss = m(xb, yb) # Computes the logits and loss by calling the model (`m`) with input (`xb`) and target (`yb`)
print(logits.shape) # print the shape of the logits tensor
print(loss) # print the computed loss

# Line generates new text by calling the `generate` method of the model (`m`)
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist())) # Generates 100 new tokens and decodes tham into human-readable text using the `decode` function



torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


### Step 6. Training the bigram model

In [ ]:
# create a Pytorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.5727508068084717


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=1000)[0].tolist()))


Iyoteng h hasbe pave pirance
Rie hicomyonthar's
Plinseard ith henoure wounonthioneir thondy, y heltieiengerofo'dsssit ey
KIN d pe wither vouprrouthercc.
hathe; d!
My hind tt hinig t ouchos tes; st yo hind wotte grotonear 'so it t jod weancotha:
h hay.JUCle n prids, r loncave w hollular s O:
HIs; ht anjx?

DUThinqunt.

LaZAnde.
athave l.
KEONH:
ARThanco be y,-hedarwnoddy scace, tridesar, wnl'shenous s ls, theresseys
PlorseelapinghiybHen yof GLUCEN t l-t E:
I hisgothers je are!-e!
QLYotouciullle'z,
Thitertho s?
NDan'spererfo cist ripl chys er orlese;
Yo jehof h hecere ek? wferommot mowo soaf yoit, ince his, t, f at. fal whetrimy bupof tor atha Bu!
JOutho f cimimave.
NEDUSt cir selle p wie wede
Ro n apenor f'Y tover witys an sh d w t e w!
CEOntiretoaveE IINpe, theck. cung.
ORIsthies hacin benqurd bll, d a r w wistatsowor ath
Fivet bloll ang a-I theeancu,
LINCI'T:
Sarry t I Ane sze t
LCKI thit,
n.
Faure ds ppplirn!
meftou ow pring, avewist th;
TENTEMETCI gienco, An he waro whiougou he s i

### Step 7. Building the "self-attention"

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [ ]:
 x[0]

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])

In [ ]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
xbow[0], xbow2[0]

(tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]))

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad() # This is a decorator used in PyTorch to disable gradient calculation. It applies to the entire function.
def estimate_loss(): # defines a function named 'estimate_loss'
    out = {} # initializes an empty dictionary named `out`, which will store the computed losses.
    model.eval() # sets the model to evaluation mode.
    for split in ['train', 'val']: # loop iterates over two splits: `'train'` and `'val'`.
        losses = torch.zeros(eval_iters) #  Initializes a tensor of zeros named `losses` with length `eval_iters`.
        for k in range(eval_iters): # loop iterates `eval_iters` times
            X, Y = get_batch(split) # fetches a batch of data based on the current split using the `get_batch` function.
            logits, loss = model(X, Y) # computes the logits and loss for the current batch by calling the model (model) with the input (X) and target (Y) tensors.
            losses[k] = loss.item() #  assigns the value of the computed loss (extracted with .item()) to the k-th index of the losses tensor.
        out[split] = losses.mean() # computes the mean of the losses tensor and assigns it to the corresponding split ('train' or 'val') in the out dictionary.
    model.train() #sets the model back to training mode. It's important to reset the mode after evaluation to enable layers like dropout and batch normalization.
    return out #eturns the out dictionary containing the average losses for both the training and validation splits.

class Head(nn.Module): # Defines a class named `Head`, which is a subclass of `nn.Module`.
    """ one head of self-attention """

    def __init__(self, head_size): # constructor method of `Head` class
        super().__init__() # Initialize the parameters and layers needed for self-attention

        # Creates a linear layer (`nn.Linear`) named `key` that maps input vectors to key vectors
        self.key = nn.Linear(n_embd, # is likely the dimensionality of the input vectors
                             head_size, # is the dimensionality of the key vectors
                             bias=False) # indicates that the linear layer won't have bias terms.

        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)

        # Creates a lower triangular matrix with ones and registers it as a buffer named `tril`
        self.register_buffer('tril', torch.tril(torch.ones(block_size, # is used to specify the size of the matrix
                                                           block_size)))

        self.dropout = nn.Dropout(dropout) # Creates a dropout layer with the specified dropout probability

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module): # Defines a class named `MultiHeadAttention`, which is a subclass of `nn.Module`
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size): # constructor method of the MultiHeadAttention class
        super().__init__() # initializes the parameters and layers needed for multiple heads of self-attention

        # creates a list of num_heads instances of the Head class
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        # creates a linear projection layer(`nn.Linear`) named `proj`
        self.proj = nn.Linear(n_embd, n_embd)
        # creates a dropout layer with the specified dropout probability
        self.dropout = nn.Dropout(dropout)

    def forward(self, x): # defines the forward pass of the MultiHeadAttention module
        out = torch.cat([h(x) for h in self.heads], dim=-1) # passes the input tensor x through each head in self.heads and concatenates their outputs along the last dimension (dim=-1).
        out = self.dropout(self.proj(out))  # applies dropout to the concatenated output and then projects it back to the original dimensionality using the linear projection layer self.proj.
        return out

class FeedFoward(nn.Module): # defines a class named FeedFoward, which is a subclass of nn.Module.
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd): # constructor method of the FeedFoward class.
        super().__init__() # calls the constructor of the parent class (nn.Module).
        self.net = nn.Sequential( # defines a sequential container (nn.Sequential) named net to organize the layers of the feedforward network.
            nn.Linear(n_embd, 4 * n_embd), # adds a linear layer (nn.Linear) to the sequential container.
            nn.ReLU(), # adds a ReLU activation function to the sequential container.
            nn.Linear(4 * n_embd, n_embd), # adds another linear layer to the sequential container.
            nn.Dropout(dropout), # adds a dropout layer to the sequential container.
        )

    def forward(self, x): # defines the forward pass of the FeedFoward module.
        return self.net(x) # passes the input tensor x through the sequential container net and returns the output.

class Block(nn.Module): #  # defines a class named Block, which is a subclass of nn.Module.
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head): # constructor method of the Block class.
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__() # calls the constructor of the parent class (nn.Module).
        head_size = n_embd // n_head # computes the size of each attention head by dividing the embedding dimension (n_embd) by the number of heads (n_head).

        # creates an instance of the MultiHeadAttention class, representing the self-attention mechanism.
        self.sa = MultiHeadAttention(n_head, # It used specified number of heads
                                     head_size) # It used specified number of computed head size

        self.ffwd = FeedFoward(n_embd) # creates an instance of the FeedFoward class, representing the feedforward neural network layer.
        self.ln1 = nn.LayerNorm(n_embd) # creates a layer normalization layer (nn.LayerNorm) named ln1.
        self.ln2 = nn.LayerNorm(n_embd) # creates another layer normalization layer (nn.LayerNorm) named ln2.

    def forward(self, x): # defines the forward pass of the Block module.
        x = x + self.sa(self.ln1(x)) # computes the output of the self-attention mechanism (self.sa) applied to the input tensor x.
        x = x + self.ffwd(self.ln2(x)) # computes the output of the feedforward layer (self.ffwd) applied to the input tensor x.
        return x #  returns the final output tensor after passing through both the self-attention mechanism and the feedforward layer.

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5090, val loss 2.5059
step 300: train loss 2.4196, val loss 2.4338
step 400: train loss 2.3504, val loss 2.3566
step 500: train loss 2.2965, val loss 2.3129
step 600: train loss 2.2410, val loss 2.2500
step 700: train loss 2.2057, val loss 2.2191
step 800: train loss 2.1633, val loss 2.1864
step 900: train loss 2.1244, val loss 2.1510
step 1000: train loss 2.1038, val loss 2.1308
step 1100: train loss 2.0707, val loss 2.1197
step 1200: train loss 2.0377, val loss 2.0800
step 1300: train loss 2.0268, val loss 2.0650
step 1400: train loss 1.9918, val loss 2.0356
step 1500: train loss 1.9697, val loss 2.0293
step 1600: train loss 1.9645, val loss 2.0499
step 1700: train loss 1.9404, val loss 2.0129
step 1800: train loss 1.9095, val loss 1.9951
step 1900: train loss 1.9067, val loss 1.9855
step 2000: train loss 1.8854, val loss 1.9948
step 2100: train loss 1.